// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/render-oss/render-mcp-server/pkg/client"
	clienta "github.com/render-oss/render-mcp-server/pkg/client/sandboxes"
)

type FakeSandboxRepoClient struct {
	ConnectSandboxFilesWithResponseStub        func(context.Context, clienta.SandboxId, string, *client.ConnectSandboxFilesParams, ...client.RequestEditorFn) (*client.ConnectSandboxFilesResponse, error)
	connectSandboxFilesWithResponseMutex       sync.RWMutex
	connectSandboxFilesWithResponseArgsForCall []FakeSandboxRepoClientConnectSandboxFilesWithResponseArgs
	connectSandboxFilesWithResponseReturns     struct {
		result1 *client.ConnectSandboxFilesResponse
		result2 error
	}
	connectSandboxFilesWithResponseReturnsOnCall map[int]struct {
		result1 *client.ConnectSandboxFilesResponse
		result2 error
	}
	ConnectSandboxRunWithResponseStub        func(context.Context, clienta.SandboxId, string, *client.ConnectSandboxRunParams, client.ConnectSandboxRunJSONRequestBody, ...client.RequestEditorFn) (*client.ConnectSandboxRunResponse, error)
	connectSandboxRunWithResponseMutex       sync.RWMutex
	connectSandboxRunWithResponseArgsForCall []FakeSandboxRepoClientConnectSandboxRunWithResponseArgs
	connectSandboxRunWithResponseReturns     struct {
		result1 *client.ConnectSandboxRunResponse
		result2 error
	}
	connectSandboxRunWithResponseReturnsOnCall map[int]struct {
		result1 *client.ConnectSandboxRunResponse
		result2 error
	}
	CreateSandboxSnapshotWithResponseStub        func(context.Context, clienta.SandboxId, *client.CreateSandboxSnapshotParams, client.CreateSandboxSnapshotJSONRequestBody, ...client.RequestEditorFn) (*client.CreateSandboxSnapshotResponse, error)
	createSandboxSnapshotWithResponseMutex       sync.RWMutex
	createSandboxSnapshotWithResponseArgsForCall []FakeSandboxRepoClientCreateSandboxSnapshotWithResponseArgs
	createSandboxSnapshotWithResponseReturns     struct {
		result1 *client.CreateSandboxSnapshotResponse
		result2 error
	}
	createSandboxSnapshotWithResponseReturnsOnCall map[int]struct {
		result1 *client.CreateSandboxSnapshotResponse
		result2 error
	}
	CreateSandboxWithResponseStub        func(context.Context, client.CreateSandboxJSONRequestBody, ...client.RequestEditorFn) (*client.CreateSandboxResponse, error)
	createSandboxWithResponseMutex       sync.RWMutex
	createSandboxWithResponseArgsForCall []FakeSandboxRepoClientCreateSandboxWithResponseArgs
	createSandboxWithResponseReturns     struct {
		result1 *client.CreateSandboxResponse
		result2 error
	}
	createSandboxWithResponseReturnsOnCall map[int]struct {
		result1 *client.CreateSandboxResponse
		result2 error
	}
	ListSandboxFilesWithResponseStub        func(context.Context, clienta.SandboxId, *client.ListSandboxFilesParams, ...client.RequestEditorFn) (*client.ListSandboxFilesResponse, error)
	listSandboxFilesWithResponseMutex       sync.RWMutex
	listSandboxFilesWithResponseArgsForCall []FakeSandboxRepoClientListSandboxFilesWithResponseArgs
	listSandboxFilesWithResponseReturns     struct {
		result1 *client.ListSandboxFilesResponse
		result2 error
	}
	listSandboxFilesWithResponseReturnsOnCall map[int]struct {
		result1 *client.ListSandboxFilesResponse
		result2 error
	}
	ListSandboxGroupsWithResponseStub        func(context.Context, *client.ListSandboxGroupsParams, ...client.RequestEditorFn) (*client.ListSandboxGroupsResponse, error)
	listSandboxGroupsWithResponseMutex       sync.RWMutex
	listSandboxGroupsWithResponseArgsForCall []FakeSandboxRepoClientListSandboxGroupsWithResponseArgs
	listSandboxGroupsWithResponseReturns     struct {
		result1 *client.ListSandboxGroupsResponse
		result2 error
	}
	listSandboxGroupsWithResponseReturnsOnCall map[int]struct {
		result1 *client.ListSandboxGroupsResponse
		result2 error
	}
	ListSandboxSnapshotsWithResponseStub        func(context.Context, clienta.SandboxGroupId, *client.ListSandboxSnapshotsParams, ...client.RequestEditorFn) (*client.ListSandboxSnapshotsResponse, error)
	listSandboxSnapshotsWithResponseMutex       sync.RWMutex
	listSandboxSnapshotsWithResponseArgsForCall []FakeSandboxRepoClientListSandboxSnapshotsWithResponseArgs
	listSandboxSnapshotsWithResponseReturns     struct {
		result1 *client.ListSandboxSnapshotsResponse
		result2 error
	}
	listSandboxSnapshotsWithResponseReturnsOnCall map[int]struct {
		result1 *client.ListSandboxSnapshotsResponse
		result2 error
	}
	ListSandboxesWithResponseStub        func(context.Context, *client.ListSandboxesParams, ...client.RequestEditorFn) (*client.ListSandboxesResponse, error)
	listSandboxesWithResponseMutex       sync.RWMutex
	listSandboxesWithResponseArgsForCall []FakeSandboxRepoClientListSandboxesWithResponseArgs
	listSandboxesWithResponseReturns     struct {
		result1 *client.ListSandboxesResponse
		result2 error
	}
	listSandboxesWithResponseReturnsOnCall map[int]struct {
		result1 *client.ListSandboxesResponse
		result2 error
	}
	RetrieveSandboxSnapshotWithResponseStub        func(context.Context, clienta.SandboxGroupId, clienta.SnapshotId, *client.RetrieveSandboxSnapshotParams, ...client.RequestEditorFn) (*client.RetrieveSandboxSnapshotResponse, error)
	retrieveSandboxSnapshotWithResponseMutex       sync.RWMutex
	retrieveSandboxSnapshotWithResponseArgsForCall []FakeSandboxRepoClientRetrieveSandboxSnapshotWithResponseArgs
	retrieveSandboxSnapshotWithResponseReturns     struct {
		result1 *client.RetrieveSandboxSnapshotResponse
		result2 error
	}
	retrieveSandboxSnapshotWithResponseReturnsOnCall map[int]struct {
		result1 *client.RetrieveSandboxSnapshotResponse
		result2 error
	}
	RetrieveSandboxWithResponseStub        func(context.Context, clienta.SandboxId, *client.RetrieveSandboxParams, ...client.RequestEditorFn) (*client.RetrieveSandboxResponse, error)
	retrieveSandboxWithResponseMutex       sync.RWMutex
	retrieveSandboxWithResponseArgsForCall []FakeSandboxRepoClientRetrieveSandboxWithResponseArgs
	retrieveSandboxWithResponseReturns     struct {
		result1 *client.RetrieveSandboxResponse
		result2 error
	}
	retrieveSandboxWithResponseReturnsOnCall map[int]struct {
		result1 *client.RetrieveSandboxResponse
		result2 error
	}
	TerminateSandboxWithResponseStub        func(context.Context, clienta.SandboxId, *client.TerminateSandboxParams, ...client.RequestEditorFn) (*client.TerminateSandboxResponse, error)
	terminateSandboxWithResponseMutex       sync.RWMutex
	terminateSandboxWithResponseArgsForCall []FakeSandboxRepoClientTerminateSandboxWithResponseArgs
	terminateSandboxWithResponseReturns     struct {
		result1 *client.TerminateSandboxResponse
		result2 error
	}
	terminateSandboxWithResponseReturnsOnCall map[int]struct {
		result1 *client.TerminateSandboxResponse
		result2 error
	}
	invocations      map[string][][]interface{}
	callOrder        []string
	invocationsMutex sync.RWMutex
}

// FakeSandboxRepoClientConnectSandboxFilesWithResponseArgs holds the arguments of one call to ConnectSandboxFilesWithResponse.
type FakeSandboxRepoClientConnectSandboxFilesWithResponseArgs struct {
	Arg1 context.Context
	Arg2 clienta.SandboxId
	Arg3 string
	Arg4 *client.ConnectSandboxFilesParams
	Arg5 []client.RequestEditorFn
}

// FakeSandboxRepoClientConnectSandboxRunWithResponseArgs holds the arguments of one call to ConnectSandboxRunWithResponse.
type FakeSandboxRepoClientConnectSandboxRunWithResponseArgs struct {
	Arg1 context.Context
	Arg2 clienta.SandboxId
	Arg3 string
	Arg4 *client.ConnectSandboxRunParams
	Arg5 client.ConnectSandboxRunJSONRequestBody
	Arg6 []client.RequestEditorFn
}

// FakeSandboxRepoClientCreateSandboxSnapshotWithResponseArgs holds the arguments of one call to CreateSandboxSnapshotWithResponse.
type FakeSandboxRepoClientCreateSandboxSnapshotWithResponseArgs struct {
	Arg1 context.Context
	Arg2 clienta.SandboxId
	Arg3 *client.CreateSandboxSnapshotParams
	Arg4 client.CreateSandboxSnapshotJSONRequestBody
	Arg5 []client.RequestEditorFn
}

// FakeSandboxRepoClientCreateSandboxWithResponseArgs holds the arguments of one call to CreateSandboxWithResponse.
type FakeSandboxRepoClientCreateSandboxWithResponseArgs struct {
	Arg1 context.Context
	Arg2 client.CreateSandboxJSONRequestBody
	Arg3 []client.RequestEditorFn
}

// FakeSandboxRepoClientListSandboxFilesWithResponseArgs holds the arguments of one call to ListSandboxFilesWithResponse.
type FakeSandboxRepoClientListSandboxFilesWithResponseArgs struct {
	Arg1 context.Context
	Arg2 clienta.SandboxId
	Arg3 *client.ListSandboxFilesParams
	Arg4 []client.RequestEditorFn
}

// FakeSandboxRepoClientListSandboxGroupsWithResponseArgs holds the arguments of one call to ListSandboxGroupsWithResponse.
type FakeSandboxRepoClientListSandboxGroupsWithResponseArgs struct {
	Arg1 context.Context
	Arg2 *client.ListSandboxGroupsParams
	Arg3 []client.RequestEditorFn
}

// FakeSandboxRepoClientListSandboxSnapshotsWithResponseArgs holds the arguments of one call to ListSandboxSnapshotsWithResponse.
type FakeSandboxRepoClientListSandboxSnapshotsWithResponseArgs struct {
	Arg1 context.Context
	Arg2 clienta.SandboxGroupId
	Arg3 *client.ListSandboxSnapshotsParams
	Arg4 []client.RequestEditorFn
}

// FakeSandboxRepoClientListSandboxesWithResponseArgs holds the arguments of one call to ListSandboxesWithResponse.
type FakeSandboxRepoClientListSandboxesWithResponseArgs struct {
	Arg1 context.Context
	Arg2 *client.ListSandboxesParams
	Arg3 []client.RequestEditorFn
}

// FakeSandboxRepoClientRetrieveSandboxSnapshotWithResponseArgs holds the arguments of one call to RetrieveSandboxSnapshotWithResponse.
type FakeSandboxRepoClientRetrieveSandboxSnapshotWithResponseArgs struct {
	Arg1 context.Context
	Arg2 clienta.SandboxGroupId
	Arg3 clienta.SnapshotId
	Arg4 *client.RetrieveSandboxSnapshotParams
	Arg5 []client.RequestEditorFn
}

// FakeSandboxRepoClientRetrieveSandboxWithResponseArgs holds the arguments of one call to RetrieveSandboxWithResponse.
type FakeSandboxRepoClientRetrieveSandboxWithResponseArgs struct {
	Arg1 context.Context
	Arg2 clienta.SandboxId
	Arg3 *client.RetrieveSandboxParams
	Arg4 []client.RequestEditorFn
}

// FakeSandboxRepoClientTerminateSandboxWithResponseArgs holds the arguments of one call to TerminateSandboxWithResponse.
type FakeSandboxRepoClientTerminateSandboxWithResponseArgs struct {
	Arg1 context.Context
	Arg2 clienta.SandboxId
	Arg3 *client.TerminateSandboxParams
	Arg4 []client.RequestEditorFn
}

func (fake *FakeSandboxRepoClient) ConnectSandboxFilesWithResponse(arg1 context.Context, arg2 clienta.SandboxId, arg3 string, arg4 *client.ConnectSandboxFilesParams, arg5 ...client.RequestEditorFn) (*client.ConnectSandboxFilesResponse, error) {
	var arg5Copy []client.RequestEditorFn
	if arg5 != nil {
		arg5Copy = make([]client.RequestEditorFn, len(arg5))
		copy(arg5Copy, arg5)
	}
	fake.connectSandboxFilesWithResponseMutex.Lock()
	ret, specificReturn := fake.connectSandboxFilesWithResponseReturnsOnCall[len(fake.connectSandboxFilesWithResponseArgsForCall)]
	fake.connectSandboxFilesWithResponseArgsForCall = append(fake.connectSandboxFilesWithResponseArgsForCall, FakeSandboxRepoClientConnectSandboxFilesWithResponseArgs{arg1, arg2, arg3, arg4, arg5Copy})
	stub := fake.ConnectSandboxFilesWithResponseStub
	fakeReturns := fake.connectSandboxFilesWithResponseReturns
	fake.recordInvocation("ConnectSandboxFilesWithResponse", []interface{}{arg1, arg2, arg3, arg4, arg5Copy})
	fake.connectSandboxFilesWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) ConnectSandboxFilesWithResponseCallCount() int {
	fake.connectSandboxFilesWithResponseMutex.RLock()
	defer fake.connectSandboxFilesWithResponseMutex.RUnlock()
	return len(fake.connectSandboxFilesWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) ConnectSandboxFilesWithResponseCalls(stub func(context.Context, clienta.SandboxId, string, *client.ConnectSandboxFilesParams, ...client.RequestEditorFn) (*client.ConnectSandboxFilesResponse, error)) {
	fake.connectSandboxFilesWithResponseMutex.Lock()
	defer fake.connectSandboxFilesWithResponseMutex.Unlock()
	fake.ConnectSandboxFilesWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) ConnectSandboxFilesWithResponseArgsForCall(i int) (context.Context, clienta.SandboxId, string, *client.ConnectSandboxFilesParams, []client.RequestEditorFn) {
	fake.connectSandboxFilesWithResponseMutex.RLock()
	defer fake.connectSandboxFilesWithResponseMutex.RUnlock()
	argsForCall := fake.connectSandboxFilesWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5
}

func (fake *FakeSandboxRepoClient) ConnectSandboxFilesWithResponseArgs() []FakeSandboxRepoClientConnectSandboxFilesWithResponseArgs {
	fake.connectSandboxFilesWithResponseMutex.RLock()
	defer fake.connectSandboxFilesWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientConnectSandboxFilesWithResponseArgs, len(fake.connectSandboxFilesWithResponseArgsForCall))
	copy(args, fake.connectSandboxFilesWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) ConnectSandboxFilesWithResponseReturns(result1 *client.ConnectSandboxFilesResponse, result2 error) {
	fake.connectSandboxFilesWithResponseMutex.Lock()
	defer fake.connectSandboxFilesWithResponseMutex.Unlock()
	fake.ConnectSandboxFilesWithResponseStub = nil
	fake.connectSandboxFilesWithResponseReturns = struct {
		result1 *client.ConnectSandboxFilesResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ConnectSandboxFilesWithResponseReturnsOnCall(i int, result1 *client.ConnectSandboxFilesResponse, result2 error) {
	fake.connectSandboxFilesWithResponseMutex.Lock()
	defer fake.connectSandboxFilesWithResponseMutex.Unlock()
	fake.ConnectSandboxFilesWithResponseStub = nil
	if fake.connectSandboxFilesWithResponseReturnsOnCall == nil {
		fake.connectSandboxFilesWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.ConnectSandboxFilesResponse
			result2 error
		})
	}
	fake.connectSandboxFilesWithResponseReturnsOnCall[i] = struct {
		result1 *client.ConnectSandboxFilesResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ConnectSandboxRunWithResponse(arg1 context.Context, arg2 clienta.SandboxId, arg3 string, arg4 *client.ConnectSandboxRunParams, arg5 client.ConnectSandboxRunJSONRequestBody, arg6 ...client.RequestEditorFn) (*client.ConnectSandboxRunResponse, error) {
	var arg6Copy []client.RequestEditorFn
	if arg6 != nil {
		arg6Copy = make([]client.RequestEditorFn, len(arg6))
		copy(arg6Copy, arg6)
	}
	fake.connectSandboxRunWithResponseMutex.Lock()
	ret, specificReturn := fake.connectSandboxRunWithResponseReturnsOnCall[len(fake.connectSandboxRunWithResponseArgsForCall)]
	fake.connectSandboxRunWithResponseArgsForCall = append(fake.connectSandboxRunWithResponseArgsForCall, FakeSandboxRepoClientConnectSandboxRunWithResponseArgs{arg1, arg2, arg3, arg4, arg5, arg6Copy})
	stub := fake.ConnectSandboxRunWithResponseStub
	fakeReturns := fake.connectSandboxRunWithResponseReturns
	fake.recordInvocation("ConnectSandboxRunWithResponse", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6Copy})
	fake.connectSandboxRunWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) ConnectSandboxRunWithResponseCallCount() int {
	fake.connectSandboxRunWithResponseMutex.RLock()
	defer fake.connectSandboxRunWithResponseMutex.RUnlock()
	return len(fake.connectSandboxRunWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) ConnectSandboxRunWithResponseCalls(stub func(context.Context, clienta.SandboxId, string, *client.ConnectSandboxRunParams, client.ConnectSandboxRunJSONRequestBody, ...client.RequestEditorFn) (*client.ConnectSandboxRunResponse, error)) {
	fake.connectSandboxRunWithResponseMutex.Lock()
	defer fake.connectSandboxRunWithResponseMutex.Unlock()
	fake.ConnectSandboxRunWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) ConnectSandboxRunWithResponseArgsForCall(i int) (context.Context, clienta.SandboxId, string, *client.ConnectSandboxRunParams, client.ConnectSandboxRunJSONRequestBody, []client.RequestEditorFn) {
	fake.connectSandboxRunWithResponseMutex.RLock()
	defer fake.connectSandboxRunWithResponseMutex.RUnlock()
	argsForCall := fake.connectSandboxRunWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5, argsForCall.Arg6
}

func (fake *FakeSandboxRepoClient) ConnectSandboxRunWithResponseArgs() []FakeSandboxRepoClientConnectSandboxRunWithResponseArgs {
	fake.connectSandboxRunWithResponseMutex.RLock()
	defer fake.connectSandboxRunWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientConnectSandboxRunWithResponseArgs, len(fake.connectSandboxRunWithResponseArgsForCall))
	copy(args, fake.connectSandboxRunWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) ConnectSandboxRunWithResponseReturns(result1 *client.ConnectSandboxRunResponse, result2 error) {
	fake.connectSandboxRunWithResponseMutex.Lock()
	defer fake.connectSandboxRunWithResponseMutex.Unlock()
	fake.ConnectSandboxRunWithResponseStub = nil
	fake.connectSandboxRunWithResponseReturns = struct {
		result1 *client.ConnectSandboxRunResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ConnectSandboxRunWithResponseReturnsOnCall(i int, result1 *client.ConnectSandboxRunResponse, result2 error) {
	fake.connectSandboxRunWithResponseMutex.Lock()
	defer fake.connectSandboxRunWithResponseMutex.Unlock()
	fake.ConnectSandboxRunWithResponseStub = nil
	if fake.connectSandboxRunWithResponseReturnsOnCall == nil {
		fake.connectSandboxRunWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.ConnectSandboxRunResponse
			result2 error
		})
	}
	fake.connectSandboxRunWithResponseReturnsOnCall[i] = struct {
		result1 *client.ConnectSandboxRunResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) CreateSandboxSnapshotWithResponse(arg1 context.Context, arg2 clienta.SandboxId, arg3 *client.CreateSandboxSnapshotParams, arg4 client.CreateSandboxSnapshotJSONRequestBody, arg5 ...client.RequestEditorFn) (*client.CreateSandboxSnapshotResponse, error) {
	var arg5Copy []client.RequestEditorFn
	if arg5 != nil {
		arg5Copy = make([]client.RequestEditorFn, len(arg5))
		copy(arg5Copy, arg5)
	}
	fake.createSandboxSnapshotWithResponseMutex.Lock()
	ret, specificReturn := fake.createSandboxSnapshotWithResponseReturnsOnCall[len(fake.createSandboxSnapshotWithResponseArgsForCall)]
	fake.createSandboxSnapshotWithResponseArgsForCall = append(fake.createSandboxSnapshotWithResponseArgsForCall, FakeSandboxRepoClientCreateSandboxSnapshotWithResponseArgs{arg1, arg2, arg3, arg4, arg5Copy})
	stub := fake.CreateSandboxSnapshotWithResponseStub
	fakeReturns := fake.createSandboxSnapshotWithResponseReturns
	fake.recordInvocation("CreateSandboxSnapshotWithResponse", []interface{}{arg1, arg2, arg3, arg4, arg5Copy})
	fake.createSandboxSnapshotWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) CreateSandboxSnapshotWithResponseCallCount() int {
	fake.createSandboxSnapshotWithResponseMutex.RLock()
	defer fake.createSandboxSnapshotWithResponseMutex.RUnlock()
	return len(fake.createSandboxSnapshotWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) CreateSandboxSnapshotWithResponseCalls(stub func(context.Context, clienta.SandboxId, *client.CreateSandboxSnapshotParams, client.CreateSandboxSnapshotJSONRequestBody, ...client.RequestEditorFn) (*client.CreateSandboxSnapshotResponse, error)) {
	fake.createSandboxSnapshotWithResponseMutex.Lock()
	defer fake.createSandboxSnapshotWithResponseMutex.Unlock()
	fake.CreateSandboxSnapshotWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) CreateSandboxSnapshotWithResponseArgsForCall(i int) (context.Context, clienta.SandboxId, *client.CreateSandboxSnapshotParams, client.CreateSandboxSnapshotJSONRequestBody, []client.RequestEditorFn) {
	fake.createSandboxSnapshotWithResponseMutex.RLock()
	defer fake.createSandboxSnapshotWithResponseMutex.RUnlock()
	argsForCall := fake.createSandboxSnapshotWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5
}

func (fake *FakeSandboxRepoClient) CreateSandboxSnapshotWithResponseArgs() []FakeSandboxRepoClientCreateSandboxSnapshotWithResponseArgs {
	fake.createSandboxSnapshotWithResponseMutex.RLock()
	defer fake.createSandboxSnapshotWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientCreateSandboxSnapshotWithResponseArgs, len(fake.createSandboxSnapshotWithResponseArgsForCall))
	copy(args, fake.createSandboxSnapshotWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) CreateSandboxSnapshotWithResponseReturns(result1 *client.CreateSandboxSnapshotResponse, result2 error) {
	fake.createSandboxSnapshotWithResponseMutex.Lock()
	defer fake.createSandboxSnapshotWithResponseMutex.Unlock()
	fake.CreateSandboxSnapshotWithResponseStub = nil
	fake.createSandboxSnapshotWithResponseReturns = struct {
		result1 *client.CreateSandboxSnapshotResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) CreateSandboxSnapshotWithResponseReturnsOnCall(i int, result1 *client.CreateSandboxSnapshotResponse, result2 error) {
	fake.createSandboxSnapshotWithResponseMutex.Lock()
	defer fake.createSandboxSnapshotWithResponseMutex.Unlock()
	fake.CreateSandboxSnapshotWithResponseStub = nil
	if fake.createSandboxSnapshotWithResponseReturnsOnCall == nil {
		fake.createSandboxSnapshotWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.CreateSandboxSnapshotResponse
			result2 error
		})
	}
	fake.createSandboxSnapshotWithResponseReturnsOnCall[i] = struct {
		result1 *client.CreateSandboxSnapshotResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) CreateSandboxWithResponse(arg1 context.Context, arg2 client.CreateSandboxJSONRequestBody, arg3 ...client.RequestEditorFn) (*client.CreateSandboxResponse, error) {
	var arg3Copy []client.RequestEditorFn
	if arg3 != nil {
		arg3Copy = make([]client.RequestEditorFn, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.createSandboxWithResponseMutex.Lock()
	ret, specificReturn := fake.createSandboxWithResponseReturnsOnCall[len(fake.createSandboxWithResponseArgsForCall)]
	fake.createSandboxWithResponseArgsForCall = append(fake.createSandboxWithResponseArgsForCall, FakeSandboxRepoClientCreateSandboxWithResponseArgs{arg1, arg2, arg3Copy})
	stub := fake.CreateSandboxWithResponseStub
	fakeReturns := fake.createSandboxWithResponseReturns
	fake.recordInvocation("CreateSandboxWithResponse", []interface{}{arg1, arg2, arg3Copy})
	fake.createSandboxWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) CreateSandboxWithResponseCallCount() int {
	fake.createSandboxWithResponseMutex.RLock()
	defer fake.createSandboxWithResponseMutex.RUnlock()
	return len(fake.createSandboxWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) CreateSandboxWithResponseCalls(stub func(context.Context, client.CreateSandboxJSONRequestBody, ...client.RequestEditorFn) (*client.CreateSandboxResponse, error)) {
	fake.createSandboxWithResponseMutex.Lock()
	defer fake.createSandboxWithResponseMutex.Unlock()
	fake.CreateSandboxWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) CreateSandboxWithResponseArgsForCall(i int) (context.Context, client.CreateSandboxJSONRequestBody, []client.RequestEditorFn) {
	fake.createSandboxWithResponseMutex.RLock()
	defer fake.createSandboxWithResponseMutex.RUnlock()
	argsForCall := fake.createSandboxWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeSandboxRepoClient) CreateSandboxWithResponseArgs() []FakeSandboxRepoClientCreateSandboxWithResponseArgs {
	fake.createSandboxWithResponseMutex.RLock()
	defer fake.createSandboxWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientCreateSandboxWithResponseArgs, len(fake.createSandboxWithResponseArgsForCall))
	copy(args, fake.createSandboxWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) CreateSandboxWithResponseReturns(result1 *client.CreateSandboxResponse, result2 error) {
	fake.createSandboxWithResponseMutex.Lock()
	defer fake.createSandboxWithResponseMutex.Unlock()
	fake.CreateSandboxWithResponseStub = nil
	fake.createSandboxWithResponseReturns = struct {
		result1 *client.CreateSandboxResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) CreateSandboxWithResponseReturnsOnCall(i int, result1 *client.CreateSandboxResponse, result2 error) {
	fake.createSandboxWithResponseMutex.Lock()
	defer fake.createSandboxWithResponseMutex.Unlock()
	fake.CreateSandboxWithResponseStub = nil
	if fake.createSandboxWithResponseReturnsOnCall == nil {
		fake.createSandboxWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.CreateSandboxResponse
			result2 error
		})
	}
	fake.createSandboxWithResponseReturnsOnCall[i] = struct {
		result1 *client.CreateSandboxResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ListSandboxFilesWithResponse(arg1 context.Context, arg2 clienta.SandboxId, arg3 *client.ListSandboxFilesParams, arg4 ...client.RequestEditorFn) (*client.ListSandboxFilesResponse, error) {
	var arg4Copy []client.RequestEditorFn
	if arg4 != nil {
		arg4Copy = make([]client.RequestEditorFn, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.listSandboxFilesWithResponseMutex.Lock()
	ret, specificReturn := fake.listSandboxFilesWithResponseReturnsOnCall[len(fake.listSandboxFilesWithResponseArgsForCall)]
	fake.listSandboxFilesWithResponseArgsForCall = append(fake.listSandboxFilesWithResponseArgsForCall, FakeSandboxRepoClientListSandboxFilesWithResponseArgs{arg1, arg2, arg3, arg4Copy})
	stub := fake.ListSandboxFilesWithResponseStub
	fakeReturns := fake.listSandboxFilesWithResponseReturns
	fake.recordInvocation("ListSandboxFilesWithResponse", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.listSandboxFilesWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) ListSandboxFilesWithResponseCallCount() int {
	fake.listSandboxFilesWithResponseMutex.RLock()
	defer fake.listSandboxFilesWithResponseMutex.RUnlock()
	return len(fake.listSandboxFilesWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) ListSandboxFilesWithResponseCalls(stub func(context.Context, clienta.SandboxId, *client.ListSandboxFilesParams, ...client.RequestEditorFn) (*client.ListSandboxFilesResponse, error)) {
	fake.listSandboxFilesWithResponseMutex.Lock()
	defer fake.listSandboxFilesWithResponseMutex.Unlock()
	fake.ListSandboxFilesWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) ListSandboxFilesWithResponseArgsForCall(i int) (context.Context, clienta.SandboxId, *client.ListSandboxFilesParams, []client.RequestEditorFn) {
	fake.listSandboxFilesWithResponseMutex.RLock()
	defer fake.listSandboxFilesWithResponseMutex.RUnlock()
	argsForCall := fake.listSandboxFilesWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeSandboxRepoClient) ListSandboxFilesWithResponseArgs() []FakeSandboxRepoClientListSandboxFilesWithResponseArgs {
	fake.listSandboxFilesWithResponseMutex.RLock()
	defer fake.listSandboxFilesWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientListSandboxFilesWithResponseArgs, len(fake.listSandboxFilesWithResponseArgsForCall))
	copy(args, fake.listSandboxFilesWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) ListSandboxFilesWithResponseReturns(result1 *client.ListSandboxFilesResponse, result2 error) {
	fake.listSandboxFilesWithResponseMutex.Lock()
	defer fake.listSandboxFilesWithResponseMutex.Unlock()
	fake.ListSandboxFilesWithResponseStub = nil
	fake.listSandboxFilesWithResponseReturns = struct {
		result1 *client.ListSandboxFilesResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ListSandboxFilesWithResponseReturnsOnCall(i int, result1 *client.ListSandboxFilesResponse, result2 error) {
	fake.listSandboxFilesWithResponseMutex.Lock()
	defer fake.listSandboxFilesWithResponseMutex.Unlock()
	fake.ListSandboxFilesWithResponseStub = nil
	if fake.listSandboxFilesWithResponseReturnsOnCall == nil {
		fake.listSandboxFilesWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.ListSandboxFilesResponse
			result2 error
		})
	}
	fake.listSandboxFilesWithResponseReturnsOnCall[i] = struct {
		result1 *client.ListSandboxFilesResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ListSandboxGroupsWithResponse(arg1 context.Context, arg2 *client.ListSandboxGroupsParams, arg3 ...client.RequestEditorFn) (*client.ListSandboxGroupsResponse, error) {
	var arg3Copy []client.RequestEditorFn
	if arg3 != nil {
		arg3Copy = make([]client.RequestEditorFn, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.listSandboxGroupsWithResponseMutex.Lock()
	ret, specificReturn := fake.listSandboxGroupsWithResponseReturnsOnCall[len(fake.listSandboxGroupsWithResponseArgsForCall)]
	fake.listSandboxGroupsWithResponseArgsForCall = append(fake.listSandboxGroupsWithResponseArgsForCall, FakeSandboxRepoClientListSandboxGroupsWithResponseArgs{arg1, arg2, arg3Copy})
	stub := fake.ListSandboxGroupsWithResponseStub
	fakeReturns := fake.listSandboxGroupsWithResponseReturns
	fake.recordInvocation("ListSandboxGroupsWithResponse", []interface{}{arg1, arg2, arg3Copy})
	fake.listSandboxGroupsWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) ListSandboxGroupsWithResponseCallCount() int {
	fake.listSandboxGroupsWithResponseMutex.RLock()
	defer fake.listSandboxGroupsWithResponseMutex.RUnlock()
	return len(fake.listSandboxGroupsWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) ListSandboxGroupsWithResponseCalls(stub func(context.Context, *client.ListSandboxGroupsParams, ...client.RequestEditorFn) (*client.ListSandboxGroupsResponse, error)) {
	fake.listSandboxGroupsWithResponseMutex.Lock()
	defer fake.listSandboxGroupsWithResponseMutex.Unlock()
	fake.ListSandboxGroupsWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) ListSandboxGroupsWithResponseArgsForCall(i int) (context.Context, *client.ListSandboxGroupsParams, []client.RequestEditorFn) {
	fake.listSandboxGroupsWithResponseMutex.RLock()
	defer fake.listSandboxGroupsWithResponseMutex.RUnlock()
	argsForCall := fake.listSandboxGroupsWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeSandboxRepoClient) ListSandboxGroupsWithResponseArgs() []FakeSandboxRepoClientListSandboxGroupsWithResponseArgs {
	fake.listSandboxGroupsWithResponseMutex.RLock()
	defer fake.listSandboxGroupsWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientListSandboxGroupsWithResponseArgs, len(fake.listSandboxGroupsWithResponseArgsForCall))
	copy(args, fake.listSandboxGroupsWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) ListSandboxGroupsWithResponseReturns(result1 *client.ListSandboxGroupsResponse, result2 error) {
	fake.listSandboxGroupsWithResponseMutex.Lock()
	defer fake.listSandboxGroupsWithResponseMutex.Unlock()
	fake.ListSandboxGroupsWithResponseStub = nil
	fake.listSandboxGroupsWithResponseReturns = struct {
		result1 *client.ListSandboxGroupsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ListSandboxGroupsWithResponseReturnsOnCall(i int, result1 *client.ListSandboxGroupsResponse, result2 error) {
	fake.listSandboxGroupsWithResponseMutex.Lock()
	defer fake.listSandboxGroupsWithResponseMutex.Unlock()
	fake.ListSandboxGroupsWithResponseStub = nil
	if fake.listSandboxGroupsWithResponseReturnsOnCall == nil {
		fake.listSandboxGroupsWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.ListSandboxGroupsResponse
			result2 error
		})
	}
	fake.listSandboxGroupsWithResponseReturnsOnCall[i] = struct {
		result1 *client.ListSandboxGroupsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ListSandboxSnapshotsWithResponse(arg1 context.Context, arg2 clienta.SandboxGroupId, arg3 *client.ListSandboxSnapshotsParams, arg4 ...client.RequestEditorFn) (*client.ListSandboxSnapshotsResponse, error) {
	var arg4Copy []client.RequestEditorFn
	if arg4 != nil {
		arg4Copy = make([]client.RequestEditorFn, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.listSandboxSnapshotsWithResponseMutex.Lock()
	ret, specificReturn := fake.listSandboxSnapshotsWithResponseReturnsOnCall[len(fake.listSandboxSnapshotsWithResponseArgsForCall)]
	fake.listSandboxSnapshotsWithResponseArgsForCall = append(fake.listSandboxSnapshotsWithResponseArgsForCall, FakeSandboxRepoClientListSandboxSnapshotsWithResponseArgs{arg1, arg2, arg3, arg4Copy})
	stub := fake.ListSandboxSnapshotsWithResponseStub
	fakeReturns := fake.listSandboxSnapshotsWithResponseReturns
	fake.recordInvocation("ListSandboxSnapshotsWithResponse", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.listSandboxSnapshotsWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) ListSandboxSnapshotsWithResponseCallCount() int {
	fake.listSandboxSnapshotsWithResponseMutex.RLock()
	defer fake.listSandboxSnapshotsWithResponseMutex.RUnlock()
	return len(fake.listSandboxSnapshotsWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) ListSandboxSnapshotsWithResponseCalls(stub func(context.Context, clienta.SandboxGroupId, *client.ListSandboxSnapshotsParams, ...client.RequestEditorFn) (*client.ListSandboxSnapshotsResponse, error)) {
	fake.listSandboxSnapshotsWithResponseMutex.Lock()
	defer fake.listSandboxSnapshotsWithResponseMutex.Unlock()
	fake.ListSandboxSnapshotsWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) ListSandboxSnapshotsWithResponseArgsForCall(i int) (context.Context, clienta.SandboxGroupId, *client.ListSandboxSnapshotsParams, []client.RequestEditorFn) {
	fake.listSandboxSnapshotsWithResponseMutex.RLock()
	defer fake.listSandboxSnapshotsWithResponseMutex.RUnlock()
	argsForCall := fake.listSandboxSnapshotsWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeSandboxRepoClient) ListSandboxSnapshotsWithResponseArgs() []FakeSandboxRepoClientListSandboxSnapshotsWithResponseArgs {
	fake.listSandboxSnapshotsWithResponseMutex.RLock()
	defer fake.listSandboxSnapshotsWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientListSandboxSnapshotsWithResponseArgs, len(fake.listSandboxSnapshotsWithResponseArgsForCall))
	copy(args, fake.listSandboxSnapshotsWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) ListSandboxSnapshotsWithResponseReturns(result1 *client.ListSandboxSnapshotsResponse, result2 error) {
	fake.listSandboxSnapshotsWithResponseMutex.Lock()
	defer fake.listSandboxSnapshotsWithResponseMutex.Unlock()
	fake.ListSandboxSnapshotsWithResponseStub = nil
	fake.listSandboxSnapshotsWithResponseReturns = struct {
		result1 *client.ListSandboxSnapshotsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ListSandboxSnapshotsWithResponseReturnsOnCall(i int, result1 *client.ListSandboxSnapshotsResponse, result2 error) {
	fake.listSandboxSnapshotsWithResponseMutex.Lock()
	defer fake.listSandboxSnapshotsWithResponseMutex.Unlock()
	fake.ListSandboxSnapshotsWithResponseStub = nil
	if fake.listSandboxSnapshotsWithResponseReturnsOnCall == nil {
		fake.listSandboxSnapshotsWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.ListSandboxSnapshotsResponse
			result2 error
		})
	}
	fake.listSandboxSnapshotsWithResponseReturnsOnCall[i] = struct {
		result1 *client.ListSandboxSnapshotsResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ListSandboxesWithResponse(arg1 context.Context, arg2 *client.ListSandboxesParams, arg3 ...client.RequestEditorFn) (*client.ListSandboxesResponse, error) {
	var arg3Copy []client.RequestEditorFn
	if arg3 != nil {
		arg3Copy = make([]client.RequestEditorFn, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.listSandboxesWithResponseMutex.Lock()
	ret, specificReturn := fake.listSandboxesWithResponseReturnsOnCall[len(fake.listSandboxesWithResponseArgsForCall)]
	fake.listSandboxesWithResponseArgsForCall = append(fake.listSandboxesWithResponseArgsForCall, FakeSandboxRepoClientListSandboxesWithResponseArgs{arg1, arg2, arg3Copy})
	stub := fake.ListSandboxesWithResponseStub
	fakeReturns := fake.listSandboxesWithResponseReturns
	fake.recordInvocation("ListSandboxesWithResponse", []interface{}{arg1, arg2, arg3Copy})
	fake.listSandboxesWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) ListSandboxesWithResponseCallCount() int {
	fake.listSandboxesWithResponseMutex.RLock()
	defer fake.listSandboxesWithResponseMutex.RUnlock()
	return len(fake.listSandboxesWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) ListSandboxesWithResponseCalls(stub func(context.Context, *client.ListSandboxesParams, ...client.RequestEditorFn) (*client.ListSandboxesResponse, error)) {
	fake.listSandboxesWithResponseMutex.Lock()
	defer fake.listSandboxesWithResponseMutex.Unlock()
	fake.ListSandboxesWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) ListSandboxesWithResponseArgsForCall(i int) (context.Context, *client.ListSandboxesParams, []client.RequestEditorFn) {
	fake.listSandboxesWithResponseMutex.RLock()
	defer fake.listSandboxesWithResponseMutex.RUnlock()
	argsForCall := fake.listSandboxesWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3
}

func (fake *FakeSandboxRepoClient) ListSandboxesWithResponseArgs() []FakeSandboxRepoClientListSandboxesWithResponseArgs {
	fake.listSandboxesWithResponseMutex.RLock()
	defer fake.listSandboxesWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientListSandboxesWithResponseArgs, len(fake.listSandboxesWithResponseArgsForCall))
	copy(args, fake.listSandboxesWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) ListSandboxesWithResponseReturns(result1 *client.ListSandboxesResponse, result2 error) {
	fake.listSandboxesWithResponseMutex.Lock()
	defer fake.listSandboxesWithResponseMutex.Unlock()
	fake.ListSandboxesWithResponseStub = nil
	fake.listSandboxesWithResponseReturns = struct {
		result1 *client.ListSandboxesResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) ListSandboxesWithResponseReturnsOnCall(i int, result1 *client.ListSandboxesResponse, result2 error) {
	fake.listSandboxesWithResponseMutex.Lock()
	defer fake.listSandboxesWithResponseMutex.Unlock()
	fake.ListSandboxesWithResponseStub = nil
	if fake.listSandboxesWithResponseReturnsOnCall == nil {
		fake.listSandboxesWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.ListSandboxesResponse
			result2 error
		})
	}
	fake.listSandboxesWithResponseReturnsOnCall[i] = struct {
		result1 *client.ListSandboxesResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxSnapshotWithResponse(arg1 context.Context, arg2 clienta.SandboxGroupId, arg3 clienta.SnapshotId, arg4 *client.RetrieveSandboxSnapshotParams, arg5 ...client.RequestEditorFn) (*client.RetrieveSandboxSnapshotResponse, error) {
	var arg5Copy []client.RequestEditorFn
	if arg5 != nil {
		arg5Copy = make([]client.RequestEditorFn, len(arg5))
		copy(arg5Copy, arg5)
	}
	fake.retrieveSandboxSnapshotWithResponseMutex.Lock()
	ret, specificReturn := fake.retrieveSandboxSnapshotWithResponseReturnsOnCall[len(fake.retrieveSandboxSnapshotWithResponseArgsForCall)]
	fake.retrieveSandboxSnapshotWithResponseArgsForCall = append(fake.retrieveSandboxSnapshotWithResponseArgsForCall, FakeSandboxRepoClientRetrieveSandboxSnapshotWithResponseArgs{arg1, arg2, arg3, arg4, arg5Copy})
	stub := fake.RetrieveSandboxSnapshotWithResponseStub
	fakeReturns := fake.retrieveSandboxSnapshotWithResponseReturns
	fake.recordInvocation("RetrieveSandboxSnapshotWithResponse", []interface{}{arg1, arg2, arg3, arg4, arg5Copy})
	fake.retrieveSandboxSnapshotWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxSnapshotWithResponseCallCount() int {
	fake.retrieveSandboxSnapshotWithResponseMutex.RLock()
	defer fake.retrieveSandboxSnapshotWithResponseMutex.RUnlock()
	return len(fake.retrieveSandboxSnapshotWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxSnapshotWithResponseCalls(stub func(context.Context, clienta.SandboxGroupId, clienta.SnapshotId, *client.RetrieveSandboxSnapshotParams, ...client.RequestEditorFn) (*client.RetrieveSandboxSnapshotResponse, error)) {
	fake.retrieveSandboxSnapshotWithResponseMutex.Lock()
	defer fake.retrieveSandboxSnapshotWithResponseMutex.Unlock()
	fake.RetrieveSandboxSnapshotWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxSnapshotWithResponseArgsForCall(i int) (context.Context, clienta.SandboxGroupId, clienta.SnapshotId, *client.RetrieveSandboxSnapshotParams, []client.RequestEditorFn) {
	fake.retrieveSandboxSnapshotWithResponseMutex.RLock()
	defer fake.retrieveSandboxSnapshotWithResponseMutex.RUnlock()
	argsForCall := fake.retrieveSandboxSnapshotWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4, argsForCall.Arg5
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxSnapshotWithResponseArgs() []FakeSandboxRepoClientRetrieveSandboxSnapshotWithResponseArgs {
	fake.retrieveSandboxSnapshotWithResponseMutex.RLock()
	defer fake.retrieveSandboxSnapshotWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientRetrieveSandboxSnapshotWithResponseArgs, len(fake.retrieveSandboxSnapshotWithResponseArgsForCall))
	copy(args, fake.retrieveSandboxSnapshotWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxSnapshotWithResponseReturns(result1 *client.RetrieveSandboxSnapshotResponse, result2 error) {
	fake.retrieveSandboxSnapshotWithResponseMutex.Lock()
	defer fake.retrieveSandboxSnapshotWithResponseMutex.Unlock()
	fake.RetrieveSandboxSnapshotWithResponseStub = nil
	fake.retrieveSandboxSnapshotWithResponseReturns = struct {
		result1 *client.RetrieveSandboxSnapshotResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxSnapshotWithResponseReturnsOnCall(i int, result1 *client.RetrieveSandboxSnapshotResponse, result2 error) {
	fake.retrieveSandboxSnapshotWithResponseMutex.Lock()
	defer fake.retrieveSandboxSnapshotWithResponseMutex.Unlock()
	fake.RetrieveSandboxSnapshotWithResponseStub = nil
	if fake.retrieveSandboxSnapshotWithResponseReturnsOnCall == nil {
		fake.retrieveSandboxSnapshotWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.RetrieveSandboxSnapshotResponse
			result2 error
		})
	}
	fake.retrieveSandboxSnapshotWithResponseReturnsOnCall[i] = struct {
		result1 *client.RetrieveSandboxSnapshotResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxWithResponse(arg1 context.Context, arg2 clienta.SandboxId, arg3 *client.RetrieveSandboxParams, arg4 ...client.RequestEditorFn) (*client.RetrieveSandboxResponse, error) {
	var arg4Copy []client.RequestEditorFn
	if arg4 != nil {
		arg4Copy = make([]client.RequestEditorFn, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.retrieveSandboxWithResponseMutex.Lock()
	ret, specificReturn := fake.retrieveSandboxWithResponseReturnsOnCall[len(fake.retrieveSandboxWithResponseArgsForCall)]
	fake.retrieveSandboxWithResponseArgsForCall = append(fake.retrieveSandboxWithResponseArgsForCall, FakeSandboxRepoClientRetrieveSandboxWithResponseArgs{arg1, arg2, arg3, arg4Copy})
	stub := fake.RetrieveSandboxWithResponseStub
	fakeReturns := fake.retrieveSandboxWithResponseReturns
	fake.recordInvocation("RetrieveSandboxWithResponse", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.retrieveSandboxWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxWithResponseCallCount() int {
	fake.retrieveSandboxWithResponseMutex.RLock()
	defer fake.retrieveSandboxWithResponseMutex.RUnlock()
	return len(fake.retrieveSandboxWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxWithResponseCalls(stub func(context.Context, clienta.SandboxId, *client.RetrieveSandboxParams, ...client.RequestEditorFn) (*client.RetrieveSandboxResponse, error)) {
	fake.retrieveSandboxWithResponseMutex.Lock()
	defer fake.retrieveSandboxWithResponseMutex.Unlock()
	fake.RetrieveSandboxWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxWithResponseArgsForCall(i int) (context.Context, clienta.SandboxId, *client.RetrieveSandboxParams, []client.RequestEditorFn) {
	fake.retrieveSandboxWithResponseMutex.RLock()
	defer fake.retrieveSandboxWithResponseMutex.RUnlock()
	argsForCall := fake.retrieveSandboxWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxWithResponseArgs() []FakeSandboxRepoClientRetrieveSandboxWithResponseArgs {
	fake.retrieveSandboxWithResponseMutex.RLock()
	defer fake.retrieveSandboxWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientRetrieveSandboxWithResponseArgs, len(fake.retrieveSandboxWithResponseArgsForCall))
	copy(args, fake.retrieveSandboxWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxWithResponseReturns(result1 *client.RetrieveSandboxResponse, result2 error) {
	fake.retrieveSandboxWithResponseMutex.Lock()
	defer fake.retrieveSandboxWithResponseMutex.Unlock()
	fake.RetrieveSandboxWithResponseStub = nil
	fake.retrieveSandboxWithResponseReturns = struct {
		result1 *client.RetrieveSandboxResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) RetrieveSandboxWithResponseReturnsOnCall(i int, result1 *client.RetrieveSandboxResponse, result2 error) {
	fake.retrieveSandboxWithResponseMutex.Lock()
	defer fake.retrieveSandboxWithResponseMutex.Unlock()
	fake.RetrieveSandboxWithResponseStub = nil
	if fake.retrieveSandboxWithResponseReturnsOnCall == nil {
		fake.retrieveSandboxWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.RetrieveSandboxResponse
			result2 error
		})
	}
	fake.retrieveSandboxWithResponseReturnsOnCall[i] = struct {
		result1 *client.RetrieveSandboxResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) TerminateSandboxWithResponse(arg1 context.Context, arg2 clienta.SandboxId, arg3 *client.TerminateSandboxParams, arg4 ...client.RequestEditorFn) (*client.TerminateSandboxResponse, error) {
	var arg4Copy []client.RequestEditorFn
	if arg4 != nil {
		arg4Copy = make([]client.RequestEditorFn, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.terminateSandboxWithResponseMutex.Lock()
	ret, specificReturn := fake.terminateSandboxWithResponseReturnsOnCall[len(fake.terminateSandboxWithResponseArgsForCall)]
	fake.terminateSandboxWithResponseArgsForCall = append(fake.terminateSandboxWithResponseArgsForCall, FakeSandboxRepoClientTerminateSandboxWithResponseArgs{arg1, arg2, arg3, arg4Copy})
	stub := fake.TerminateSandboxWithResponseStub
	fakeReturns := fake.terminateSandboxWithResponseReturns
	fake.recordInvocation("TerminateSandboxWithResponse", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.terminateSandboxWithResponseMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSandboxRepoClient) TerminateSandboxWithResponseCallCount() int {
	fake.terminateSandboxWithResponseMutex.RLock()
	defer fake.terminateSandboxWithResponseMutex.RUnlock()
	return len(fake.terminateSandboxWithResponseArgsForCall)
}

func (fake *FakeSandboxRepoClient) TerminateSandboxWithResponseCalls(stub func(context.Context, clienta.SandboxId, *client.TerminateSandboxParams, ...client.RequestEditorFn) (*client.TerminateSandboxResponse, error)) {
	fake.terminateSandboxWithResponseMutex.Lock()
	defer fake.terminateSandboxWithResponseMutex.Unlock()
	fake.TerminateSandboxWithResponseStub = stub
}

func (fake *FakeSandboxRepoClient) TerminateSandboxWithResponseArgsForCall(i int) (context.Context, clienta.SandboxId, *client.TerminateSandboxParams, []client.RequestEditorFn) {
	fake.terminateSandboxWithResponseMutex.RLock()
	defer fake.terminateSandboxWithResponseMutex.RUnlock()
	argsForCall := fake.terminateSandboxWithResponseArgsForCall[i]
	return argsForCall.Arg1, argsForCall.Arg2, argsForCall.Arg3, argsForCall.Arg4
}

func (fake *FakeSandboxRepoClient) TerminateSandboxWithResponseArgs() []FakeSandboxRepoClientTerminateSandboxWithResponseArgs {
	fake.terminateSandboxWithResponseMutex.RLock()
	defer fake.terminateSandboxWithResponseMutex.RUnlock()
	args := make([]FakeSandboxRepoClientTerminateSandboxWithResponseArgs, len(fake.terminateSandboxWithResponseArgsForCall))
	copy(args, fake.terminateSandboxWithResponseArgsForCall)
	return args
}

func (fake *FakeSandboxRepoClient) TerminateSandboxWithResponseReturns(result1 *client.TerminateSandboxResponse, result2 error) {
	fake.terminateSandboxWithResponseMutex.Lock()
	defer fake.terminateSandboxWithResponseMutex.Unlock()
	fake.TerminateSandboxWithResponseStub = nil
	fake.terminateSandboxWithResponseReturns = struct {
		result1 *client.TerminateSandboxResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) TerminateSandboxWithResponseReturnsOnCall(i int, result1 *client.TerminateSandboxResponse, result2 error) {
	fake.terminateSandboxWithResponseMutex.Lock()
	defer fake.terminateSandboxWithResponseMutex.Unlock()
	fake.TerminateSandboxWithResponseStub = nil
	if fake.terminateSandboxWithResponseReturnsOnCall == nil {
		fake.terminateSandboxWithResponseReturnsOnCall = make(map[int]struct {
			result1 *client.TerminateSandboxResponse
			result2 error
		})
	}
	fake.terminateSandboxWithResponseReturnsOnCall[i] = struct {
		result1 *client.TerminateSandboxResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeSandboxRepoClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSandboxRepoClient) CallOrder() []string {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	order := make([]string, len(fake.callOrder))
	copy(order, fake.callOrder)
	return order
}

func (fake *FakeSandboxRepoClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	fake.callOrder = append(fake.callOrder, key)
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
